### ISSUE TITLE
[Issue] 账号登录失败

### ISSUE THREAD

**Issue by AllenXiao95** [genchsusu/xddq-assistant#84]
今天更新后无法正常登录, 已拉取最新代码, 日志如下:
```
xddq-assistant % yarn start
yarn run v1.22.22
$ node app.js
2024-09-12 15:53:04.090 info   [Login] 尝试使用token登录...
2024-09-12 15:53:04.378 warn   [Login] token登录失败, 尝试使用用户名密码登录...
2024-09-12 15:53:04.378 info   正在连接服务器...
AxiosError: read ECONNRESET
    at Function.AxiosError.from (/xddq-assistant/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/xddq-assistant/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/xddq-assistant/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Axios.request (/xddq-assistant/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AuthService.secondRequest (/xddq-assistant/src/services/authService.js:112:30)
    at async AuthService.Login (/xddq-assistant/src/services/authService.js:207:36)
    at async default (/xddq-assistant/src/loaders/index.js:24:24)
    at async start (/xddq-assistant/app.js:36:5) {
  syscall: 'read',
  code: 'ECONNRESET',
  errno: -54,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'axios/1.7.2',
      'Content-Length': '356',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'https://apimyh5.37.com/index.php?c=sdk-login&a=act_login',
    data: 'is_self=1&pid=37h5&ptoken=NTM4YVh5VjhXb1ZtQ0ZlT29zVm1PUU0rZUZCQ29IRlRnRW9NSHBwTWxGekxCVU12M0xUYlVIeW1HSUdBdnFkTDVLQ0hMeDBSM1p0elpiR0c1aUh5YTYxdVdmUmtYVGVvTmJLK0E2b3dxR3NFcnhESUdXcEtqL0pFQXdhcjRLZWtYTjZKMGFZazk0Z0JNcHozRjBZVE0zV04xUUgwdUdoeGZMSE5EdWhnekNNMUNJUFdDbUxaRFp5TXFETUU3Y0NKQTRLZkN1bmQ1VUJJa05rWnV5QncyVnRLR1lrS3VzV2lzeDJXbnZUMDRn&puid=tgzhj5157951'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/index.php?c=sdk-login&a=act_login',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'apimyh5.37.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/index.php',
      search: '?c=sdk-login&a=act_login'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 356,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '356',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /index.php?c=sdk-login&a=act_login HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: axios/1.7.2\r\n' +
        'Content-Length: 356\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: apimyh5.37.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/index.php?c=sdk-login&a=act_login',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'apimyh5.37.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://apimyh5.37.com/index.php?c=sdk-login&a=act_login',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
2024-09-12 15:53:04.785 error  read ECONNRESET
```

**Comment by luzzhong** [comment]
拉取最新代码后要修改account.js，看下[account.json.sample](https://github.com/genchsusu/xddq-assistant/blob/master/account.json.sample)

**Comment by AllenXiao95** [comment]
我再次确认了下, 是系统代理问题导致的, 域名添加白名单后问题解决了. 如果造成困扰十分抱歉! Thank you for your assistance.
