### ISSUE TITLE
收到星宿奖励会报错

### ISSUE THREAD

**Issue by zeroT6** [genchsusu/xddq-assistant#94]
[仙宫管理] 收获礼物 STAR-TRIAL-GIFT-3106182-3106182036611-slvna
node:internal/buffer:1066
      throw new ERR_BUFFER_OUT_OF_BOUNDS('length');
            ^
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Op.writeStringBuffer [as fn] (/Users/bytedance/Downloads/game/node_modules/protobufjs/src/writer_buffer.js:61:13)
    at BufferWriter.finish (/Users/bytedance/Downloads/game/node_modules/protobufjs/src/writer.js:453:14)
    at GameNetMgr.sendPbMsg (file:///Users/bytedance/Downloads/game/src/game/net/GameNetMgr.js:134:55)
    at PalaceMgr.checkReward (file:///Users/bytedance/Downloads/game/src/game/mgr/PalaceMgr.js:33:29)
    at MsgRecvMgr.SendGiftSyncMsg (file:///Users/bytedance/Downloads/game/src/game/common/MsgRecvMgr.js:167:24)
    at GameNetMgr.resvHandler (file:///Users/bytedance/Downloads/game/src/game/net/GameNetMgr.js:205:35)
    at GameNetMgr.parseArrayBuffMsg (file:///Users/bytedance/Downloads/game/src/game/net/GameNetMgr.js:182:22)
    at parseMessage (file:///Users/bytedance/Downloads/game/src/game/net/NetSocket.js:171:54)
    at NetSocket.readNextMsgData (file:///Users/bytedance/Downloads/game/src/game/net/NetSocket.js:179:13) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}

**Comment by genchsusu** [comment]
已知问题，不知道如何复现，可以过滤STAR开头的先跳过。。。
